language: cpp
compiler:
  - gcc
  - clang
env:
  - SUBTARGET=arcade MAME=mamearcade64
  - SUBTARGET=mess   MAME=mess64
script:
  - if [ $CC == 'clang' ];
    then make -j2 linux_x64_clang OPT_FLAGS="-fPIC" && ./$MAME -validate;
    else make -j2 OPTIMIZE=0 OPT_FLAGS="-fPIC"      && ./$MAME -validate;
    fi
sudo: false
addons:
  apt:
    sources:
      - debian-sid
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang-3.7
      - libqt5qml5
      - libsdl2-dev
      - libfontconfig1-dev
notifications:
  email: false
