name: CI - Ubuntu latest release

on: [push]

jobs:
  test_Ubuntu_Latest:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-ttf-dev libfontconfig-dev qt5-default
    - name: Build
      run: make TOOLS=1 -j3
    - name: Test
      run: ./mame64 -validate

