name: CI - macOS latest release

on: [push]

jobs:
  test_MacOS_Latest:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          brew update
          brew install sdl2
    - name: Build
      run: make USE_LIBSDL=1 TOOLS=1 -j3 all
    - name: Test
      run: ./mame64 -validate

