name: CI - macOS latest release

on: [push]

jobs:
  test_MacOS_Latest:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make USE_BUNDLED_LIB_SDL2=1 TOOLS=1 -j3 all
    - name: Test
      run: ./mame64 -verify

