name: CI

on: [push]

jobs:
  test_Ubuntu_Latest:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev libsdl2-ttf-dev libfontconfig-dev qt5-default
    - name: Build
      run: make TARGET=mame TOOLS=1 PTR64=1 OPTIMIZE=3 REGENIE=1 -j3
    - name: Validate
      run: ./mame64 -validate



  test_MacOS_Latest:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
          brew update
          brew install sdl2 pkg-config
    - name: Build
      run: make TARGET=mame TOOLS=1 PTR64=1 OPTIMIZE=3 REGENIE=1 USE_LIBSDL=1 -j3
    - name: Validate
      run: ./mame64 -validate



  test_Win_MINGW_64_Latest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
      with:
          update: true
    - name: Install Dependencies
      run: |
          msys2do pacman -Syu --noconfirm
          msys2do pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
          msys2do pacman -Scc --noconfirm
    - name: Build
      run: msys2do make TARGET=mame TOOLS=1 SEPARATE_BIN=1 PTR64=1 OPTIMIZE=3 REGENIE=1 MINGW64="/mingw64" -j3
    - name: Validate
      run: |
          $process = (Start-Process -PassThru -NoNewWindow -Wait ".\build\mingw-gcc\bin\x64\Release\mame64.exe" -ArgumentList "-validate")
          Write-Host "Process finished with return code: " $process.ExitCode

  test_Win_MSVC:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1 
      with:
          update: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Install Dependencies
      run: |
          msys2do pacman -Syu --noconfirm
          msys2do pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain
          msys2do pacman -Scc --noconfirm
    - name: Generate build files
      run: msys2do make TARGET=mame TOOLS=1 PTR64=1 OPTIMIZE=3 REGENIE=1 MINGW64="/mingw64" -j3 vs2019
    - name: Build
      run: msbuild "build\projects\windows\mame\vs2019\mame.sln" /m:2 /p:ContinueOnError=false /p:StopOnFirstFailure=true /property:Configuration=Release /property:Platform=x64
    - name: Test
      run: Start-Process -NoNewWindow -Wait ".\mame64.exe" -ArgumentList "-validate"

  test_Win_MINGW_64_Latest_releasebuild:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: numworks/setup-msys2@v1
      with:
          update: true
    - name: Install Dependencies
      run: |
          msys2do pacman -Syu --noconfirm
          msys2do pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
          msys2do pacman -Scc --noconfirm
    - name: Build
      run: msys2do make TARGET=mame TOOLS=1 SEPARATE_BIN=1 PTR64=1 OPTIMIZE=3 SYMBOLS=1 SYMLEVEL=1 REGENIE=1 MINGW64="/mingw64" -j3
    - name: Validate
      run: |
          $process = (Start-Process -PassThru -NoNewWindow -Wait ".\build\mingw-gcc\bin\x64\Release\mame64.exe" -ArgumentList "-validate")
          Write-Host "Process finished with return code: " $process.ExitCode
    - name: Free disk space
      run: Remove-Item -Force -Recurse ".\build\mingw-gcc\obj"
    - name: Package
      run: msys2do make -f dist.mak PTR64=1
    - uses: actions/upload-artifact@v1
      with:
          name: mame64
          path: build/release

